import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";



const robotoCondensed = Roboto_Condensed ({
  subsets: ["latin"],
  weight: ['400', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoCondensed.variable}`}>
        
        <Header/>
        
        <main>

          {children}

        </main>
      
      </body>
    </html>
  );
}
