import { Roboto_Condensed } from "next/font/google";
import { Comic_Neue } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";


const robotoCondensed = Roboto_Condensed ({
  subsets: ["latin"],
  weight: ['400', '700'],
});


const comicNeue = Comic_Neue({
  weight: ["300", "400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: '--font-comic'
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoCondensed.variable} ${comicNeue.variable}`}>
        
        <Header/>
        
        <main>

          {children}

        </main>

        <Footer/>
      
      </body>
    </html>
  );
}
